rails/awesome_blog/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

rails/awesome_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/awesome_blog/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user # one model object

  validates :content, presence: true, length: { maximum: 250 }
  mount_uploader :picture, PictureUploader
end

rails/awesome_blog/app/models/relationship.rb
class Relationship < ApplicationRecord
end

rails/awesome_blog/app/models/user.rb
class User < ApplicationRecord
    has_many :microposts #array object

    before_save { email.downcase! }

    validates :name, presence: true

    #constant variable
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    has_secure_password

    def active_relationships
        Relationship.where(follower_id: id)
        # SELECT * FROM relationships WHERE
        # follower_id = id 
    end

    def passive_relationships
        Relationship.where(followed_id: id)
    end

    def followers
        ids = passive_relationships.pluck(:follower_id)
        User.where(id: ids)
    end

    def following
        ids = active_relationships.pluck(:followed_id)
        User.where(id: ids)
    end

    def follow(other_user)
        Relationship.create(
            follower_id: id,
            followed_id: other_user.id
        )
    end

    def relationship(other_user)
        active_relationships.find_by(
            followed_id: other_user.id
        )
    end

    def feed
        ids = following.pluck(:id)
        ids << id

        Micropost.where(user_id: ids)
        # SELECT * FROM microposts WHERE user_id = [2, 3] OR user_id = 1
    end
end

rails/awesome_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

rails/awesome_blog/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    def create
        @micropost = current_user.microposts.new(micropost_params)

        if @micropost.save
            redirect_to root_url
        else
            @microposts = current_user.microposts.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
            render "users/home_feed"
        end
    end

    def destroy
        micropost = Micropost.find(params[:id])

        if current_user == micropost.user
            micropost.destroy
            flash[:info] = "Micropost deleted."
        else
            flash[:danger] = "You can't do that."
        end

        redirect_to request.referrer || root_url
    end

    private
        def micropost_params
            params.require(:micropost).permit(:content, :picture)
        end
end

rails/awesome_blog/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        other_user = User.find(params[:followed_id])
        current_user.follow(other_user)

        redirect_to other_user
    end

    def destroy
        relationship = Relationship.find(params[:id])
        other_user = User.find(relationship.followed_id)
        relationship.destroy

        redirect_to other_user
    end
end

rails/awesome_blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # check if email exists in our database
    # check if password is correct
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Successfully logged in!"
      redirect_to user #user_url(user.id)
    else
      flash[:danger] = "Invalid credentials. Please try again."
      redirect_to login_url
    end
  end

  def destroy
    log_out
    flash[:info] = "You are logged out."
    redirect_to root_url
  end
end

rails/awesome_blog/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = Micropost.new
      @microposts = current_user.feed.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
      render "users/home_feed"
    end
  end

  def about
  end

  def contact
  end
end

rails/awesome_blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index, :show]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user.id) #/users/:id
    else
      render "new" #new.html.erb
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render "edit"
    end
  end

  def following
    @user = User.find(params[:id])
    @title = "Following"
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    render "users/follow"
  end

  def followers
    @user = User.find(params[:id])
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render "users/follow"
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def require_login
      unless logged_in?
        flash[:info] = "Please log in."
        redirect_to login_url
      end
    end
end

rails/awesome_blog/app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title = "AwesomeBlog"

        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

rails/awesome_blog/app/helpers/microposts_helper.rb
module MicropostsHelper
end

rails/awesome_blog/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

rails/awesome_blog/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
    end

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end
end

rails/awesome_blog/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails/awesome_blog/app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email)
        url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    
        image_tag(url)
    end
end

rails/awesome_blog/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <%= link_to "awesomeblog", root_path, class: "navbar-brand" %>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>

            <% unless logged_in? %>
                <li class="nav-item">
                    <%= link_to "Sign up", new_user_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Log in", login_path, class: "nav-link" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Users", users_path, class: "nav-link" %>
                </li>

                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbar-dropdown" data-toggle="dropdown">
                        <%= current_user.name %>
                    </a>

                    <div class="dropdown-menu">
                        <%= link_to "Profile", current_user, class: "dropdown-item" %>
                        <%= link_to "Settings", edit_user_path(current_user.id), class: "dropdown-item" %>
                        <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

rails/awesome_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container mt-3">
      <% if flash.any? %>
        <% flash.each do |type, msg| %>
          <div class="alert alert-<%= type %>">
            <%= msg %>
          </div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>

    <%#= debug session[:user_id] %>
  </body>
</html>

rails/awesome_blog/app/views/microposts/_micropost.html.erb
<div class="media mb-4 border-bottom pb-3">
    <%= gravatar_for micropost.user %>

    <div class="media-body ml-3">
        <h5><%= link_to micropost.user.name, micropost.user %></h5>
        <div><%= micropost.content %></div>

        <% if micropost.picture? %>
            <div>
                <%= image_tag micropost.picture.url, class: "mw-100" %>
            </div>
        <% end %>

        <small class="text-muted">Posted <%= time_ago_in_words(micropost.created_at) %> ago</small>
    </div>

    <%= link_to micropost_path(micropost), method: :delete,
                data: { confirm: "Are you sure you want to delete?" } do %>
        <i class="fa fa-times float-right text-muted"></i>
    <% end %>
</div>

rails/awesome_blog/app/views/static_pages/about.html.erb
<% provide :title, "This is the about page" %>

<div class="jumbotron">
    <h1>About us</h1>
    <p>This is just a simple micro-blogging site,
    where you can post and interact with other
    people.</p>
</div>

rails/awesome_blog/app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>

<div class="jumbotron">
    <h1>Contact us</h1>
    <p>...</p>
</div>

rails/awesome_blog/app/views/static_pages/home.html.erb
<div class="jumbotron">
    <h1>Awesomeblog</h1>
    <p>Welcome to awesomeblog!</p>
</div>

rails/awesome_blog/app/views/users/_user_info.html.erb
<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">
            <div class="media">
                <%= gravatar_for @user %>

                <div class="media-body ml-3">
                    <h1><%= @user.name %></h1>
                    <p><%= @user.email %></p>
                    
                    <%# Check if current_user is following this user %>

                    <% unless current_user == @user %>
                        <% unless current_user.relationship(@user) %>
                            <%= button_to "Follow", relationships_path,
                                    params: { followed_id: @user.id },
                                    class: "btn btn-sm btn-success" %>
                        <% else %>
                            <%= button_to "Unfollow", relationship_path(current_user.relationship(@user)),
                                    method: :delete,
                                    class: "btn btn-sm btn-danger" %>
                        <% end %>
                    <% end %>

                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="row">
                <div class="col">
                    <h3>
                        <%= link_to @user.microposts.count, @user %>
                    </h3>
                    microposts
                </div>
                <div class="col">
                    <h3>
                        <%= link_to @user.active_relationships.count, following_user_path(@user) %>
                    </h3>
                    following
                </div>
                <div class="col">
                    <h3>
                        <%= link_to @user.passive_relationships.count, followers_user_path(@user) %>
                    </h3>
                    followers
                </div>
            </div>
        </div>
    </div>
</div>

rails/awesome_blog/app/views/users/edit.html.erb
<div class="row">
    <div class="col-md-6 mx-auto">
        <h1 class="text-center">Settings</h1>
        <hr>

        <%= form_for @user do |f| %>
            <%= render "shared/errors", object: f.object %>

            <div class="form-group">
                <%= f.label :name %>

                <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :email %>

                <%= f.text_field :email, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :password %>

                <%= f.password_field :password, class: "form-control" %>
            </div>

            <%= f.submit "Edit account", class: "btn btn-primary btn-block" %>
        <% end %>
    </div>
</div>

rails/awesome_blog/app/views/users/follow.html.erb
<%= render "users/user_info" %>

<div class="row">
    <div class="col-md-8 mx-auto">
        <h3><%= @title %></h3>
        <hr>

        <% @users.each do |user| %>
            <div class="media mb-3">
                <%= gravatar_for user %>

                <div class="media-body ml-3">
                    <h4><%= link_to user.name, user %></h4>
                </div>
            </div>
        <% end %>

        <div class="paginate">
            <%= will_paginate %>
        </div>
    </div>
</div>

rails/awesome_blog/app/views/users/home_feed.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <%= gravatar_for current_user %>

                <h1><%= current_user.name %></h1>
                <%= current_user.email %>

                <hr>

                <div class="row">
                    <div class="col">
                        <h5><%= link_to @microposts.count, current_user %></h5>
                        <small>microposts</small>
                    </div>
                    <div class="col">
                        <h5><%= current_user.active_relationships.count %></h5>
                        <small>following</small>
                    </div>
                    <div class="col">
                        <h5><%= current_user.passive_relationships.count %></h5>
                        <small>followers</small>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <!-- Uses the microposts#create -->
                <%= form_for @micropost do |f| %>
                    <%= render "shared/errors", object: f.object %>

                    <div class="form-group">
                        <%= f.text_area :content, placeholder: "Share your thoughts...", rows: 5, class: "form-control" %>
                    </div>

                    <div class="form-group">
                        <%= f.file_field :picture %>
                    </div>

                    <%= f.submit "Post", class: "btn btn-primary btn-block" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <h3>Feed</h3>
        <hr>
        <%= render @microposts %> 

        <div class="paginate">
            <%= will_paginate @microposts %>
        </div>
    </div>
</div>

rails/awesome_blog/app/views/users/index.html.erb
<h1 class="text-center">Users</h1>
<hr>

<div class="paginate mb-3">
    <%= will_paginate %>
</div>
''
<div class="row">
    <% @users.each do |user| %>
        <div class="col-md-6 mb-2">
            <%= gravatar_for user %>
            <%= link_to user.name, user_path(user.id) %>
        </div>
    <% end %>
</div>

<div class="paginate mt-4">
    <%= will_paginate %>
</div>

rails/awesome_blog/app/views/users/new.html.erb
<div class="row">
    <div class="col-md-6 mx-auto">
        <h1 class="text-center">Sign up</h1>
        <p class="text-center">Join us for free!</p>

        <%= form_for @user do |f| %>
            <%= render "shared/errors", object: f.object %>

            <div class="form-group">
                <%= f.label :name %>

                <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :email %>

                <%= f.text_field :email, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :password %>

                <%= f.password_field :password, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>

                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>

            <%= f.submit "Create an account", class: "btn btn-primary btn-block" %>
        <% end %>
    </div>
</div>

rails/awesome_blog/app/views/users/show.html.erb
<%= render "users/user_info" %>

<div>
    <%= render @microposts %>
</div>

<div class="paginate">
    <%= will_paginate @microposts %>
</div>